// FUNDAMENTAL OF JAVA SCRIPT
// foreach ,map ,filter, find ,indexOf

// let arr=[1,2,3,4]
// arr.forEach(function(val) {
//     console.log(val +" hello")
// });

// #MAP
// let arr=[1,2,3,4]
// arr.map(function(val){
//     console.log(val*2)
// })

// #FIND
// let arr=[1,2,3,4]
// let ans =arr.find(function(val){
//     if(val==2) return true;
// })
// console.log(ans);


// #OBJECT
// let obj={
//     name:"Rahul",
//     age:22
// }
// console.log(obj.name) //or ham ae bhi likh sakte hai obj['name']
// obj.age=30;
// console.log(obj['age']) //object me age ki value change ho gai hai if we use || object.freeze(obj) ||so  value chnge nahi hogi